
platform :ios,’8.0’

target 'password_package' do
    
pod 'IQKeyboardManager'
pod 'Masonry'
pod 'SVProgressHUD'
pod 'FMDB'
pod 'MBProgressHUD'
pod 'AppCenter'
pod 'Masonry'
pod 'AFNetworking'
pod 'JSONModel'
pod 'iCloudDocumentSync'
pod 'DYFAuthIDAndGestureLock'
pod 'SDWebImage'
pod 'MMPopupView'
pod 'WCDB'
pod 'HWPopController'
pod 'JHUD'
pod 'SCIndexView'
pod 'PYSearch'
pod 'TZImagePickerController'
pod 'CYLTabBarController'
pod 'ProgressHUD'
pod 'LEETheme'


end

